name: OrangeFox - æ„å»º

# Credits to:
# https://github.com/TeamWin
# https://gitlab.com/OrangeFox
# https://github.com/azwhikaru for Recovery Builder Template
# And all Contributors in every repositories I used
# è°ƒæ•™è¯´æ˜
# Limeä¼˜åŒ–ä¸ç¼–è¾‘ä¿®å¤
# åœ¨åŸæœ‰åŸºç¡€ä¸Šæ·»åŠ å¯¹OF14.1çš„æ”¯æŒ

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'OrangeFox Manifest Branch'
        required: true
        default: '12.1'
        type: choice
        options:
        - 14.1
        - 12.1
        - 11.0
        - 10.0
      DEVICE_TREE:
        description: 'OrangeFoxè®¾å¤‡æ ‘'
        required: true
        default: 'https://github.com/LimeBlogs/twrp_device_redmi12c'
      DEVICE_TREE_BRANCH:
        description: 'OrangeFoxè®¾å¤‡æ ‘åˆ†æ”¯'
        required: true
        default: 'main'
      DEVICE_PATH:
        description: 'æŒ‡å®šè®¾å¤‡è·¯å¾„'
        required: true
        default: 'device/xiaomi/earth'
      DEVICE_NAME:
        description: 'æŒ‡å®šè®¾å¤‡ä»£å·'
        required: true
        default: 'earth'
      BUILD_TARGET:
        description: 'æ„å»ºç›®æ ‡'
        required: true
        default: 'recovery'
        type: choice
        options:
        - recovery

jobs:
  build:
    name: ğŸ  ç”± ${{ github.actor }} æ„å»ºREC
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: âœ… æ£€æŸ¥
      uses: actions/checkout@v4
              
    - name: ğŸ§¹ æ¸…ç†
      uses: rokibhasansagar/slimhub_actions@main

    - name: ğŸš¢ Swapç©ºé—´
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24
      
    - name: ğŸ¤– æ„å»ºç¯å¢ƒ
      run: |
        sudo apt install aria2 -y
        git clone https://gitlab.com/OrangeFox/misc/scripts.git -b master
        cd scripts
        sudo bash setup/android_build_env.sh
      
    - name: ğŸ™ï¸ åˆå§‹åŒ–æ¸…å•
      if: inputs.MANIFEST_BRANCH == '11.0' || inputs.MANIFEST_BRANCH == '12.1' || inputs.MANIFEST_BRANCH == '14.1'
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
        cd ${GITHUB_WORKSPACE}/OrangeFox
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git clone https://gitlab.com/OrangeFox/sync.git -b master
        cd sync
        ./orangefox_sync.sh --branch ${{ inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}

    - name: ğŸŒ³ å…‹éš†è®¾å¤‡æ ‘
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
        git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./${{ inputs.DEVICE_PATH }}
        cd ${{ inputs.DEVICE_PATH }}
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: ğŸ¦Š æ„å»ºOrangeFox
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
        set +e
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        set -e
        lunch twrp_${{ inputs.DEVICE_NAME }}-eng && mka recoveryimage
        
        if [ ! -f "out/target/product/${{ inputs.DEVICE_NAME }}/recovery.img" ]; then
            echo "âŒ ä¸¥é‡é”™è¯¯ï¼šæœªæ£€æµ‹åˆ°RECé•œåƒ"
            echo "è¯·æ£€æŸ¥ BoardConfig.mkæˆ–è®¾å¤‡æ ‘æ˜¯å¦é…ç½®æ­£ç¡®ã€‚"
            exit 1
        else
            echo "âœ… æˆåŠŸï¼šRECé•œåƒæ„å»ºå®Œæ¯•"
        fi

    - name: ğŸ§¶ è®¾ç½®å‘è¡Œç‰ˆ
      run: |
        echo "BUILD_DATE=$(TZ=Asia/Manila date +%Y%m%d)" >> $GITHUB_ENV
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}

        DEVICE_TREE_URL="${{ inputs.DEVICE_TREE }}"
        if [[ "${DEVICE_TREE_URL}" == *.git ]]; then
          DEVICE_TREE_URL="${DEVICE_TREE_URL%.git}"
        fi
        echo "DEVICE_TREE_URL=${DEVICE_TREE_URL}" >> $GITHUB_ENV

    - name: ğŸ“¦ æ•´ç†åˆ·æœºåŒ…
      run: |
        # 1. åˆ›å»ºä¸€ä¸ªä¸´æ—¶çš„å¹²å‡€æ–‡ä»¶å¤¹
        mkdir -p upload_artifacts
        
        echo "æ­£åœ¨æœå¯» recovery.img ..."
        # åœ¨ out ç›®å½•ä¸‹æŸ¥æ‰¾ recovery.imgï¼Œå¿½ç•¥ä¸­é—´äº§ç‰©ï¼Œå¹¶å¤åˆ¶åˆ°ä¸Šä¼ ç›®å½•
        find . -path "*/out/target/product/*/*.img" -name "recovery.img" -exec cp {} upload_artifacts/ \;
        
        echo "æ­£åœ¨æœå¯» OrangeFox zip åŒ… ..."
        # æŸ¥æ‰¾ä»¥ .zip ç»“å°¾ä¸”åå­—åŒ…å« OrangeFox çš„æ–‡ä»¶ï¼Œæ’é™¤ common ç›®å½•çš„å¹²æ‰°
        find . -type f -name "*OrangeFox*.zip" ! -path "*/common/*" -exec cp {} upload_artifacts/ \;
        
        echo "=== å‡†å¤‡ä¸Šä¼ çš„æ–‡ä»¶æ¸…å• ==="
        ls -R upload_artifacts/

    - name: ğŸ¥ ä¸Šä¼ è‡³å‘è¡Œç‰ˆ
      uses: softprops/action-gh-release@v2
      if: success()
      with:
        # åªä¸Šä¼ åœ¨è¿™ä¸ªæ–‡ä»¶å¤¹é‡Œçš„ä¸œè¥¿ï¼Œç»å¯¹å¹²å‡€
        files: upload_artifacts/*
        name: OrangeFox Recovery for ${{ inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          # OrangeFox ${{ inputs.MANIFEST_BRANCH }}
          ğŸš€æ„å»º: ${{ github.run_id }}
          ğŸ“±è®¾å¤‡: ${{ inputs.DEVICE_NAME }}
          ğŸ¦ŠOrangeFoxç‰ˆæœ¬: ${{ inputs.MANIFEST_BRANCH }}
          
